# Generated by Django 5.0.6 on 2024-09-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='producto',
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_producto', models.PositiveIntegerField()),
                ('cliente', models.ManyToManyField(related_name='clientes', to='myapp.cliente')),
                ('producto', models.ManyToManyField(related_name='productos', to='myapp.producto')),
            ],
        ),
    ]
