# Generated by Django 5.2.1 on 2025-06-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10)),
                ('creatinina', models.FloatField()),
                ('tfg', models.IntegerField()),
                ('presion_arterial_sistolica', models.IntegerField()),
                ('presion_arterial_diastolica', models.IntegerField()),
                ('obesidad', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=2)),
                ('albumina', models.IntegerField()),
                ('estadio_erc', models.IntegerField()),
            ],
        ),
    ]
