# Generated by Django 5.2.1 on 2025-06-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_remove_paciente_estadio_erc_alter_paciente_albumina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
