# Generated by Django 5.2.1 on 2025-06-03 15:00

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_paciente_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='creatinina',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, help_text='eg. 2025-06-03', validators=[django.core.validators.MinValueValidator(datetime.date(2025, 6, 3)), django.core.validators.MaxValueValidator(datetime.date(2026, 6, 3))]),
        ),
    ]
