# Generated by Django 5.2.1 on 2025-06-03 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_alter_paciente_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
