# Generated by Django 5.2.1 on 2025-06-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0007_alter_paciente_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='fecha',
        ),
    ]
