# Generated by Django 5.2.3 on 2025-06-23 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0009_alter_paciente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
