# Generated by Django 5.2.3 on 2025-06-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0011_alter_paciente_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('1', 'Masculino'), ('0', 'Femenino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='obesidad',
            field=models.CharField(choices=[('1', 'Sí'), ('0', 'No')], max_length=1),
        ),
    ]
