# Generated by Django 5.2.3 on 2025-06-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0012_alter_paciente_genero_alter_paciente_obesidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='erc',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
